stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

variables:
  GIT_STRATEGY: clone
  GRADLE_OPTS: "-Dorg:gradle.daemon=false"

build:
  stage: build
  tags:
    - dalfcs_docker_autoscale
  image: gradle:7.3.3-jdk17-alpine
  script:
    - chmod +x gradlew
    - ./gradlew assemble --scan

test:
  stage: test
  tags:
    - dalfcs_docker_autoscale
  image: gradle:7.3.3-jdk17-alpine
#  script:
#    - ./gradlew check
  script:
    - chmod +x gradlew
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml

deploy-test:
  stage: deploy
  tags:
    - dalfcs_docker_autoscale
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$TEST_HEROKU_APPLICATION_NAME --api-key=$TEST_HEROKU_API_KEY
  only:
    - release
    - fix-deployment


deploy-production:
  stage: deploy
  tags:
    - dalfcs_docker_autoscale
  image: ruby:2.6
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$PRODUCTION_HEROKU_APPLICATION_NAME --api-key=$PRODUCTION_HEROKU_API_KEY
  only:
    - main
